name: Build Windows Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: latest
        vulkan-components: Vulkan-Headers, Vulkan-Loader, Glslang, SPIRV-Tools

    - name: Check Vulkan SDK
      run: |
        echo "VULKAN_SDK=$env:VULKAN_SDK"
        $env:VULKAN_SDK\Bin\vulkaninfo.exe

    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Configure CMake
      run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUD_ENABLE_PROFILING=OFF -DBUD_ENABLE_AFTERMATH=ON -DBUD_BUILD_SAMPLES=ON -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build build --config Release -- -j

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: BudEngine-Windows-Release
        path: build/
